spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url:
    username:
    password:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect:
          nodeValue: org.hibernate.dialect.MySQL5Dialect
          storage_engine: innodb
        format_sql: true
    show-sql: true
